---
- name: "OS fingerprinting "
  debug:
    msg:
    - " ansible_os_family: {{ hostvars[inventory_hostname].ansible_os_family }} "
    - " ansible_distribution: {{ hostvars[inventory_hostname].ansible_distribution }}"
    - " ansible_distribution_major_version: {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - " ansible_distribution_release: {{ hostvars[inventory_hostname].ansible_distribution_release }}"
    - " ansible_distribution_version: {{ hostvars[inventory_hostname].ansible_distribution_version }}"

- name: "Install docker {{ ansible_distribution }}-{{ ansible_distribution_version }}"
  include_tasks: "{{ ansible_distribution }}_{{ ansible_distribution_version }}_install.yml"

# - name: "Configure docker {{ ansible_distribution }}-{{ ansible_distribution_version }}"
#   include_tasks: "configure/configure_{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
#
# - name: "Ensure group docker exists"
#   group:
#       name: docker
#       state: present
#
# - name: "Manage Docker as a non-root user"
#   user:
#       name: vagrant
#       groups: docker
#       append: yes
